### ISSUE TITLE
Refrain from doing language comparisons

### ISSUE THREAD

**Issue by gusthoff** [raph-amiard/intro-to-ada#1]
I think we should refrain from doing language comparisons. They should be limited to cases where the Ada syntax might be confusing and mentioning a different language might prevent the reader from jumping into wrong conclusions. In other words, the language comparison would actually be used for clarification in these cases. Other kind of comparisons (especially against C/C++) could be left for separate tutorials.

**Comment by raph-amiard** [comment]
I forgot about this issue! Let me close it now: As discussed live, we will not refrain from doing language comparisons, but we will try to make them as general as possible, and ultimately put them in blocks that are outside of the normal flow of the text.

**Comment by raph-amiard** [comment]
Also we will ultimately put links to the booklet comparing Ada with C and C++ when applicable !
