### ISSUE TITLE
Use one line per paragraph for text

### ISSUE THREAD

**Issue by gusthoff** [raph-amiard/intro-to-ada#2]
Having manual line wrap (due to e.g. 80-character limitation) might be annoying in some cases. For example, when words are added to a single phrase, the whole paragraph might need to be "realigned". It is especially difficult to review the differences, since comparison tools might indicate that the whole paragraph changed.

My suggestion is that we try using one line per paragraph and see if that works better. Of course, this suggestion only applies to raw text: for source-code, using the 80-char limit is perfectly fine.

**Comment by raph-amiard** [comment]
Hello Gustavo,

I don't necessarily agree or disagree in the abstract, but doing that won't be possible anyway because we need to follow AdaCore's coding style, which is to always wrap (in all languages, including rst).

It's applied pretty much everywhere automatically, except in GitHub repos because the style checkers don't run there, but even then I don't think we should diverge.

**Comment by gusthoff** [comment]
Coding style can be adapted, right? ;-)
Either way, if you agree, we could simply use the suggested approach and just apply line breaking when the text is ready for publication.

**Comment by raph-amiard** [comment]
Hey Gustavo,

You have not understood what I said I think. I don't lean one way or the other regarding this specific rule. However I am inflexible about respecting the company's agreed upon coding style. This is a company wide policy. At some point it might be enforced as a post commit hook (this is already done for internal repos). If you want to change it you can launch a proposal internally (although I would not encourage you to do so to be honest).

On the argument itself, I feel the need to point out that for diff tools, it won't make a difference for line based diff tools (whole paragraph will be highlighted), and every "more clever" diff tool that I use (GitHub's included) is clever enough to highlight real changes in a reasonable fashion. Here is what meld does for example:
n
![meld](https://user-images.githubusercontent.com/478727/35558948-98ae561a-05a9-11e8-9b2f-92d990b77039.png)

Rewrapping paragraphs is a pain, although very minor for me - select paragraph + gq in vim and I imagine every decent text editor can do something similar.

And then you have the benefit of having a properly formatted document in every situation, even in bad viewers/editors.

Anyway, one big benefit of having company wide policies on that kind of stuff is to avoid repeating this kind of debates that have no good answer :) So closing this.
